# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Living and Leading with Love
email: to-be-added@domain.com
description: Through the generous grant support of the Lilly Endowment, Brescia University will begin a youth theological institute for high school students beginning in August 2016 called, “Living and Leading with Love”. Fifteen to 20 students will participate a year-long program that will include theological reflections, online learning, service opportunities, retreats, prayer experiences, and a ten-day, intensive on-ground experience at Brescia University during the summer to conclude.  # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: to-be-added
github_username:  l3siteadmin

# Build settings
markdown: kramdown
